In [2]:
import numpy as np 
from tensornetwork import ncon
import scipy.linalg as LA 


In [10]:
t1 = np.random.rand(1,3,4)

one = np.array(1.).reshape(1,1)

print(np.shape(t1),np.shape(one))

t2 = ncon([one,t1], [[1,-1],[1,-2,-3]])

print(t1-t2)

(1, 3, 4) (1, 1)
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [13]:
sz = np.array([[1., 1.1] , [1.2, 1.3]])

ZkZ = np.kron(sz,sz)
ZkZr = ZkZ.reshape(2,2,2,2)
ZkZrp = ZkZr.transpose(0,2,1,3)

ZncZ = ncon([sz,sz],[[-1,-2],[-3,-4]])

print(np.ravel(ZkZrp))
print(np.ravel(ZncZ))

eZ_k_eZ = np.kron(LA.expm(sz), LA.expm(sz))
e_ZkZ =  LA.expm(np.kron(sz,sz))

print(np.ravel(eZ_k_eZ))
print(np.ravel(e_ZkZ))


[1.   1.1  1.2  1.3  1.1  1.21 1.32 1.43 1.2  1.32 1.44 1.56 1.3  1.43
 1.56 1.69]
[1.   1.1  1.2  1.3  1.1  1.21 1.32 1.43 1.2  1.32 1.44 1.56 1.3  1.43
 1.56 1.69]
[24.3946776  21.2637931  21.2637931  18.53473549 23.1968652  30.1938939
 20.21971145 26.31872096 23.1968652  20.21971145 30.1938939  26.31872096
 22.05786703 28.71133195 28.71133195 37.37172689]
[39.90966681 42.44238832 42.44238832 46.29594287 46.30078726 51.48486363
 50.50466495 55.06855456 46.30078726 50.50466495 51.48486363 55.06855456
 55.09599813 60.07478679 60.07478679 66.50356032]
