# Test that the power method is really a thing 

In [3]:
import numpy as np
from numpy import linalg as LA

In [43]:
vt1 = np.array([1,2,3,4])
vt2 = np.array([2,4,6,12])
print( vt1/vt2)
print(np.divide(vt1,vt2))

print(0.1*vt1)

m1 = np.array([[ 1.,2,3,4,5],[2,3,4,4,4],[2,3,5,6,3],[2,2,2,3,1],[5,4,4,3,1]])
m1h = m1 + np.transpose(m1)



[0.5        0.5        0.5        0.33333333]
[0.5        0.5        0.5        0.33333333]
[0.1 0.2 0.3 0.4]


In [33]:
ee=LA.eig(m1h)
e1 = ee[1][:,0]

np.divide(m1h @ e1 , e1)

In [38]:
v1 = np.array([2.,2,2,2,2])

In [41]:
v2 = m1h @ v1
v2n = v2/ (v2 @ v2)
for j in range(0,10):
    v2 = m1h @ v2n
    v2n = v2/ np.sqrt(v2 @ v2)
print(v2n)
print( v2n / e1)

[0.38404341 0.44271646 0.53302311 0.42892463 0.43407697]
[-0.99999996 -0.99999999 -1.         -1.00000001 -1.00000004]


In [ ]:
[-0.38404342, -0.6145912 ,  0.47470902,  0.45848067,  0.19807862],