In [1]:
import numpy as np 
import scipy.linalg as LA

from tensornetwork import ncon

In [2]:
sz = np.array([[1,0.],[0,-1]])


In [3]:


phi = np.mod(np.random.rand(1),2*np.pi)[0]
theta = np.mod(np.random.rand(1),np.pi)[0]
psi = np.mod(np.random.rand(1),4.*np.pi)[0]

uL = LA.expm(1j*sz*phi/2.) 
uR = LA.expm(1j*sz*psi/2.) 

cc =  np.cos( theta/2 )
iss = 1j*np.sin(theta/2)

V = np.array( [[ cc, iss ], [iss, cc  ]])


U1 = uL @ V @ uR 

U1dag = np.conj(U1).transpose()

print(np.real_if_close(np.round(U1 @ U1dag ,10)))
print(np.real_if_close(np.round(U1dag @ U1 ,10)))

print(np.real_if_close(np.round(ncon( [U1, U1.conj()], [[1,-1],[1,-2]]),10 )))
print(np.real_if_close(np.round(ncon( [U1, U1.conj()], [[-1,1],[-2,1]]),10 )))

[[1. 0.]
 [0. 1.]]
[[ 1. -0.]
 [-0.  1.]]
[[ 1. -0.]
 [-0.  1.]]
[[1. 0.]
 [0. 1.]]


In [4]:
ct3 = np.zeros((2,2,2))
ct3[0,0,0]=1
ct3[1,1,1]=1

ct4 = np.zeros((2,2,2,2))
ct4[0,0,0,0]=1
ct4[1,1,1,1]=1



In [5]:
U1c = U1.conj()
U1-U1c

array([[0.+0.85029052j, 0.+0.49688699j],
       [0.+0.49688699j, 0.-0.85029052j]])

In [10]:
AA=ncon( [U1, U1c, ct4, U1c, U1], [[-1,1],[2,-2],[1,2,3,4],[-3,3],[4,-4]])

B=ncon( [U1, ct3, U1c], [[-1,1],[1,-2,3],[-3,3]])
BB = ncon([B, np.conj(B)], [[-1,1,-3],[-2,1,-4]])

C = ncon( [U1, ct3, U1c], [[-1,1],[1,2,-3],[2,-2]])
CC = ncon([C, np.conj(C)], [[-1,-2,1],[-3,-4,1]])

print([np.max(i) for i in (AA,BB,CC)])

print( np.ravel(np.isclose(AA,BB)) )
print( np.ravel(np.isclose(AA,CC)) )
print( np.ravel(np.isclose(BB,CC)))

print(np.ravel(AA))
print(np.ravel(BB))
print(np.ravel(CC))

[(0.8649140586330117+0j), (0.8649140586330116+0j), (0.8649140586330117+0j)]
[ True False  True False False  True False  True  True False  True False
 False  True False  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[ True False  True False False  True False  True  True False  True False
 False  True False  True]
[ 0.86491406+0.00000000e+00j  0.16808617+1.45057916e-01j
  0.01238393-2.21678590e-01j  0.09382429-9.71864925e-02j
  0.16808617-1.45057916e-01j  0.13508594+2.60208521e-18j
 -0.08241575-1.07032030e-01j -0.01238393+2.21678590e-01j
  0.01238393+2.21678590e-01j -0.08241575+1.07032030e-01j
  0.13508594-2.60208521e-18j -0.16808617-1.45057916e-01j
  0.09382429+9.71864925e-02j -0.01238393-2.21678590e-01j
 -0.16808617+1.45057916e-01j  0.86491406+0.00000000e+00j]
[ 0.86491406+0.j          0.01238393+0.22167859j  0.01238393-0.22167859j
  0.13508594+0.j          0.01238393-0.22167859j  0.13508594+0.j
 -0.1342454 -0.01504602j -0.0123